openapi: 3.0.0
info:
  title: Quotes API
  version: 1.0.0
servers:
  - description: Test server
    url: http://localhost:8083

paths:
  /metrics:
    get:
      summary: Получение метрик заказов
      operationId: getMetrics
      tags:
        - Metrics
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MetricsDto'

components:
  schemas:
    MetricsDto:
      type: "object"
      properties:
        totalOrders:
          type: "integer"
        hourly:
          type: array
          items:
            $ref: '#/components/schemas/MetricsDtoHourly'

    MetricsDtoHourly:
      type: "object"
      properties:
        hour:
          type: "string"
        orderCount:
          type: "integer"