global:
  scrape_interval: 15s  # Интервал опроса по умолчанию

scrape_configs:
  - job_name: 'example-app'
    metrics_path: '/actuator/prometheus'  # Эндпоинт метрик вашего приложения
    static_configs:
      - targets: ["my-app:8080"]  # IP-адрес или имя хоста вашего приложения