##
## Запуск сервисов
##

#version: '3.8'

services:
  user-service:
    build: .
    container_name: app
    depends_on:
      - db-postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-postgres:5432/userService
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    ports:
      - "8090:8080"

  db-postgres:
    image: 'postgres:13-alpine'
    container_name: db-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=userService
    ports:
      - "5432:5432"