server:
  port: 80

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE

spring:
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8200/realms/App
          jwk-set-uri: http://${keycloak.host:localhost}:${keycloak.port:8200}/realms/App/protocol/openid-connect/certs
  application:
    name: Gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: UserService
          uri: http://${user.service.host:localhost}:${user.service.port:8081}
          predicates:
            - Path=/api/v1/users/**
        - id: OrderService
          uri: http://${order.service.host:localhost}:${order.service.port:8082}
          predicates:
            - Path=/api/v1/products/**, /api/v1/orders/**, /api/v1/categories/**