##
## Запуск сервисов
##

#version: '3.8'
networks:
  spring-cloud-network:
    driver: bridge

services:
  gateway:
    build:
      ./gateway
    container_name: gateway
    ports:
      - "80:80"
    environment:
      - USER_SERVICE_HOST=user-service
      - USER_SERVICE_PORT=8081
      - ORDER_SERVICE_HOST=order-service
      - ORDER_SERVICE_PORT=8082
    networks:
      - spring-cloud-network

  user-service:
    build: ./userService
    container_name: userService
    depends_on:
      - db-postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-postgres:5432/pizzeria
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
      - SERVER_PORT=8081
    ports:
      - "8081:8081"
    networks:
      - spring-cloud-network

  order-service:
    build: ./orderService
    container_name: orderService
    depends_on:
      - db-postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-postgres:5432/pizzeria
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    ports:
      - "8082:8080"
    networks:
      - spring-cloud-network

  db-postgres:
    image: 'postgres:13-alpine'
    container_name: db-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pizzeria
    ports:
      - "5432:5432"
    networks:
      - spring-cloud-network