name: CheckStyle

on:
  push:
    branches:
      - 'feature/**'
jobs:
  userService:
    runs-on: ubuntu-latest
    steps:
      - name: Step_1 - Checkout
        uses: actions/checkout@v4
      - name: Step_2 - Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Step_3 - Run checkstyle
        working-directory: ./UserService/
        run: mvn -P check-code-style validate