name: Tests

on:
  pull_request:
    branches:
      - master
jobs:
  userService:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Maven UserService Package
        working-directory: ./UserService/
        run: mvn -B clean package -DskipTests
      - name: Run UserService Tests
        working-directory: ./UserService/
        run: mvn -B test --file pom.xml
  orderService:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Maven OrderService Package
        working-directory: ./OrderService/
        run: mvn -B clean package -DskipTests
      - name: Run OrderService Tests
        working-directory: ./OrderService/
        run: mvn -B test --file pom.xml